# Generated by Django 5.2.8 on 2026-08-29 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.TextField(help_text='Direct URL to city cover photo')),
                ('is_popular', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('category', models.CharField(choices=[('street_food', 'Street Food'), ('local_food', 'Local Food'), ('traditional_food', 'Traditional Food'), ('dessert', 'Dessert & Sweets'), ('breakfast', 'Breakfast & Snacks'), ('beverage', 'Beverages & Drinks'), ('main_course', 'Main Course')], default='local_food', max_length=50)),
                ('diet_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('egg', 'Contains Egg'), ('vegan', 'Vegan')], default='veg', max_length=20)),
                ('description', models.TextField()),
                ('why_famous', models.TextField(help_text='Why this dish is iconic in this city')),
                ('price_range', models.CharField(help_text='e.g. ₹50 - ₹120', max_length=50)),
                ('is_must_try', models.BooleanField(default=False)),
                ('image_url', models.TextField(help_text='Food item photo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='api.city')),
            ],
            options={
                'ordering': ['-is_must_try', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('address', models.TextField()),
                ('area', models.CharField(help_text='Locality or Area name, e.g. FC Road, Chandni Chowk', max_length=150)),
                ('specialty', models.CharField(help_text='Top specialty dishes served here', max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('street_food', 'Street Food Stall'), ('traditional_eatery', 'Traditional Eatery'), ('family_restaurant', 'Family Restaurant'), ('cafe', 'Cafe & Bakery'), ('sweet_shop', 'Sweet & Snack Shop'), ('heritage_spot', 'Heritage Iconic Spot')], default='traditional_eatery', max_length=50)),
                ('diet_type', models.CharField(choices=[('pure_veg', 'Pure Vegetarian'), ('non_veg_served', 'Non-Vegetarian & Veg'), ('veg_friendly', 'Vegetarian Friendly')], default='pure_veg', max_length=20)),
                ('price_range', models.CharField(help_text='e.g. ₹100 - ₹200 for two', max_length=100)),
                ('price_tier', models.CharField(choices=[('budget', 'Budget Friendly (Under ₹150)'), ('moderate', 'Moderate (₹150 - ₹400)'), ('premium', 'Premium (₹400+)')], default='budget', max_length=20)),
                ('image_url', models.TextField(help_text='Primary display photo')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('latitude', models.FloatField(default=18.5204)),
                ('longitude', models.FloatField(default=73.8567)),
                ('opening_hours', models.CharField(default='8:00 AM - 10:00 PM', max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('map_link', models.URLField(blank=True, max_length=500)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('why_special', models.TextField(blank=True, help_text='Why this spot is a hidden gem or must visit')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='api.city')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_hidden_gem', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPlaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_specialty', models.BooleanField(default=True)),
                ('item_price', models.CharField(blank=True, max_length=50)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodplace')),
            ],
            options={
                'unique_together': {('place', 'food')},
            },
        ),
        migrations.AddField(
            model_name='foodplace',
            name='featured_foods',
            field=models.ManyToManyField(blank=True, related_name='recommended_places', through='api.FoodPlaceItem', to='api.food'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField()),
                ('must_try_dish', models.CharField(blank=True, help_text="User's top dish recommendation", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.foodplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('food_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.foodplace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'food_place')},
            },
        ),
    ]
